import engine from './engine.mjs'
import adapters from './adapters.mjs'
import transforms3d from './transforms-3d.mjs'
import scene3dWebgl from './scene-3d-webgl.mjs'
import exportsCheck from './exports.mjs'
import demos from './demos.mjs'
import editor from './editor.mjs'
import docs from './docs.mjs'
import showcase from './showcase.mjs'
import embed from './embed.mjs'
import editorSteps from './editor-steps.mjs'
import landing from './landing.mjs'
import learn from './learn.mjs'
import examplePages from './example-pages.mjs'
import learnEditor from './learn-editor.mjs'

export const checks = [engine, adapters, transforms3d, scene3dWebgl, exportsCheck, demos, editor, docs, showcase, landing, learn, examplePages, learnEditor, embed, editorSteps]
